### ISSUE TITLE
{"vp.baseDir": "docs"} not work

### ISSUE THREAD

**Issue by spectereye** [0x-jerry/vscode-vitepress#13]
Thanks for this awesome extensions!
just find an issue, `{"vp.baseDir": "docs"}` (or "/docs", "./docs") does not work if place .md files in `/docs` though `vitepress dev docs` works

**Comment by 0x-jerry** [comment]
Please try this configuration with the new version.

```json
{
  "vp.docsDir": "docs",
}
```
