### ISSUE TITLE
Error: there is no registered task type 'SimpleServer'

### ISSUE THREAD

**Issue by Veetaha** [0x-jerry/vscode-vitepress#19]
**Describe the bug**
I tried to start the dev server with the new version, but the preview tab doesn't show up. All I see in the logs is this line:
```
Error: there is no registered task type 'SimpleServer'. Did you miss installing an extension that provides a corresponding task provider?
```

**To Reproduce**

1. Clone the repo `https://github.com/elastio/bon`
2. Add config `"vp.docsDir": "website"` to `settings.json`
3. Open any page, for example the root `website/src/index.md`

**Expected behavior**
A preview tab should show up.

**Screenshots**

https://github.com/user-attachments/assets/921d0b28-b0e9-42b1-a5a4-58c7d36869fb

**Plugin version:** `v0.3.0`

**Additional context**
I'm running VSCode via SSH.

**Comment by 0x-jerry** [comment]
Thanks for reporting this. I think this error can be safely ignored. And, I can't reproduce this situation.

I guess it's due to some other factors. Maybe you need to wait a little longer for the preview tab to open. Can you try waiting a moment after VitePress starts?



https://github.com/user-attachments/assets/316b1160-b9c2-4c3b-b338-096551ba7f04

**Comment by 0x-jerry** [comment]
I have checked the internal logic, and there is an edge case that will prevent the preview tab from opening. I have changed it to skip that check. You can try the latest version.

**Comment by Veetaha** [comment]
I've found this in the vscode dev tools, if this is relevant:

![image](https://github.com/user-attachments/assets/dde9f120-58e1-4278-8e91-17b1fc36586a)

Text version:

```
[Extension Host] fetch url failed TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SimpleServer._detectServer (/home/veetaha/.vscode-server/extensions/fantasy.vp-preview-0.3.0/node_modules/.pnpm/@0x-jerry+vscode-simple-server@0.3.2/node_modules/@0x-jerry/vscode-simple-server/dist/index.js:143:9)
    at SimpleServer.start (/home/veetaha/.vscode-server/extensions/fantasy.vp-preview-0.3.0/node_modules/.pnpm/@0x-jerry+vscode-simple-server@0.3.2/node_modules/@0x-jerry/vscode-simple-server/dist/index.js:162:36)
    at Y0.h (file:///home/veetaha/.vscode-server/cli/servers/Stable-912bb683695358a54ae0c670461738984cbb5b95/server/out/vs/workbench/api/node/extensionHostProcess.js:114:32825)
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
A @ ipc.net.ts:1022
(anonymous) @ ipc.net.ts:879
B @ event.ts:1243
fire @ event.ts:1274
acceptChunk @ ipc.net.ts:394
(anonymous) @ ipc.net.ts:350
B @ event.ts:1243
fire @ event.ts:1274
fire @ event.ts:1441
(anonymous) @ managedSocket.ts:108
B @ event.ts:1243
fire @ event.ts:1274
$onDidManagedSocketHaveData @ mainThreadManagedSockets.ts:77
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:308
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
```

**Comment by 0x-jerry** [comment]
Yes, this is the edge case, if the extension check server fails to start, the preview tab will not open. I have changed to force ignore this check.

> I've found this in the vscode dev tools, if this is relevant:
> 
> ![image](https://private-user-images.githubusercontent.com/36276403/382440554-dde9f120-58e1-4278-8e91-17b1fc36586a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MTcyNTYsIm5iZiI6MTczMDUxNjk1NiwicGF0aCI6Ii8zNjI3NjQwMy8zODI0NDA1NTQtZGRlOWYxMjAtNThlMS00Mjc4LThlOTEtMTdiMWZjMzY1ODZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDAzMDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTRkY2Q2OGI5OTQ4ZWIxY2NmYTg3MWQzZWFkM2YzMjIxMDhlOGNmYzU4OGNhMWFhZTQ0NzliY2I4NWQ1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nx_y10_4h1dbIZs010Aqkrz460vf-Rtb3SZae9PPjZs)
> 
> Text version:
> 
> ```
> [Extension Host] fetch url failed TypeError: fetch failed
>     at node:internal/deps/undici/undici:13185:13
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at SimpleServer._detectServer (/home/veetaha/.vscode-server/extensions/fantasy.vp-preview-0.3.0/node_modules/.pnpm/@0x-jerry+vscode-simple-server@0.3.2/node_modules/@0x-jerry/vscode-simple-server/dist/index.js:143:9)
>     at SimpleServer.start (/home/veetaha/.vscode-server/extensions/fantasy.vp-preview-0.3.0/node_modules/.pnpm/@0x-jerry+vscode-simple-server@0.3.2/node_modules/@0x-jerry/vscode-simple-server/dist/index.js:162:36)
>     at Y0.h (file:///home/veetaha/.vscode-server/cli/servers/Stable-912bb683695358a54ae0c670461738984cbb5b95/server/out/vs/workbench/api/node/extensionHostProcess.js:114:32825)
> uGi @ console.ts:137
> $logExtensionHostMessage @ mainThreadConsole.ts:39
> S @ rpcProtocol.ts:458
> Q @ rpcProtocol.ts:443
> M @ rpcProtocol.ts:373
> L @ rpcProtocol.ts:299
> (anonymous) @ rpcProtocol.ts:161
> B @ event.ts:1243
> fire @ event.ts:1274
> fire @ ipc.net.ts:652
> A @ ipc.net.ts:1022
> (anonymous) @ ipc.net.ts:879
> B @ event.ts:1243
> fire @ event.ts:1274
> acceptChunk @ ipc.net.ts:394
> (anonymous) @ ipc.net.ts:350
> B @ event.ts:1243
> fire @ event.ts:1274
> fire @ event.ts:1441
> (anonymous) @ managedSocket.ts:108
> B @ event.ts:1243
> fire @ event.ts:1274
> $onDidManagedSocketHaveData @ mainThreadManagedSockets.ts:77
> S @ rpcProtocol.ts:458
> Q @ rpcProtocol.ts:443
> M @ rpcProtocol.ts:373
> L @ rpcProtocol.ts:308
> (anonymous) @ rpcProtocol.ts:161
> B @ event.ts:1243
> fire @ event.ts:1274
> fire @ ipc.net.ts:652
> l.onmessage @ localProcessExtensionHost.ts:378
> ```

**Comment by Veetaha** [comment]
I tried the new version, tried waiting longer (not that I didn't wait longer before though), but the preview still doesn't show up =(

That type error in dev tools is still there.

**Comment by 0x-jerry** [comment]
> fetch url failed TypeError: fetch failed

this error now can safely ignored.

Can you confirm if the Simple Browser extension exists?

![image](https://github.com/user-attachments/assets/f5b04fb2-8a86-4ac1-9bfe-7bc573ff03a3)

**Comment by Veetaha** [comment]
Yeah it exists. 

![image](https://github.com/user-attachments/assets/319f39b1-d01b-4922-8f0f-13df12a5849d)

**Comment by Veetaha** [comment]
I can also open it manually at the localhost:4001 address

![image](https://github.com/user-attachments/assets/03a4b462-3e0f-4dbc-9df9-a3f77573b373)

**Comment by Veetaha** [comment]
Double-checked again on 0.2.2 - it works fine in this version. The preview tab opens. I also don't see that fetch TypeError in the dev tools on this version

**Comment by 0x-jerry** [comment]
> Double-checked again on 0.2.2 - it works fine in this version. The preview tab opens. I also don't see that fetch TypeError in the dev tools on this version

Because I didn't print the fetch TypeError on v0.2.2. LOL

I will check the changes after v0.2.2

**Comment by Veetaha** [comment]
Here is my client VSCode version:
```
Version: 1.95.0 (user setup)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by Veetaha** [comment]
I'll go to sleep for now. I'm available in the Vue's discord server under `@mare_stare` for chat, in DMs, or for a call

**Comment by 0x-jerry** [comment]
Sure, good night.

**Comment by 0x-jerry** [comment]
Unfortunately, I can't figure out what's wrong, but I've added a log output channel. Can you try the latest version and provide the output channel information?

You need to enable the output channel by setting `"vp.debug": true` and reload VSCode.


https://github.com/user-attachments/assets/229f776d-2c31-4838-b9c7-f5d8a527ce77

**Comment by Veetaha** [comment]
Hi, I tried with the new debug logging, and I think it shows the problem better:
```
2024-11-02 14:55:45.100 [info] Starting server...
2024-11-02 14:55:45.100 [info] VitePress server starting...
2024-11-02 14:55:45.100 [info] Starting server with command: npx vitepress --host --port 4001 dev "website"
2024-11-02 14:55:45.616 [info] VitePress server is not ready yet... fetch failed
2024-11-02 14:55:45.653 [info] VitePress server is not ready yet... fetch failed
2024-11-02 14:55:46.155 [info] VitePress server is not ready yet... fetch failed
2024-11-02 14:55:46.657 [info] VitePress server is not ready yet... fetch failed
2024-11-02 14:55:47.160 [info] VitePress server is not ready yet... fetch failed
2024-11-02 14:55:47.678 [info] Resolved url: tasks -> undefined
2024-11-02 14:55:50.317 [info] load VitePress config...
2024-11-02 14:55:51.105 [info] resolve VitePress url: /home/veetaha/work/bon/website/src/reference/builder/member/into.md -> undefined
2024-11-02 14:55:51.105 [info] Resolved url: /home/veetaha/work/bon/website/src/reference/builder/member/into.md -> undefined
2024-11-02 14:55:55.152 [info] Resolved url: fantasy.vp-preview.VitePress Preview -> undefined
```

The logs stopped at this point

**Comment by Veetaha** [comment]
I've managed to start a dev instance of the extension from your repo, I'll try to debug this further on my end

**Comment by 0x-jerry** [comment]
> Hi, I tried with the new debug logging, and I think it shows the problem better:
> 
> ```
> 2024-11-02 14:55:45.100 [info] Starting server...
> 2024-11-02 14:55:45.100 [info] VitePress server starting...
> 2024-11-02 14:55:45.100 [info] Starting server with command: npx vitepress --host --port 4001 dev "website"
> 2024-11-02 14:55:45.616 [info] VitePress server is not ready yet... fetch failed
> 2024-11-02 14:55:45.653 [info] VitePress server is not ready yet... fetch failed
> 2024-11-02 14:55:46.155 [info] VitePress server is not ready yet... fetch failed
> 2024-11-02 14:55:46.657 [info] VitePress server is not ready yet... fetch failed
> 2024-11-02 14:55:47.160 [info] VitePress server is not ready yet... fetch failed
> 2024-11-02 14:55:47.678 [info] Resolved url: tasks -> undefined
> 2024-11-02 14:55:50.317 [info] load VitePress config...
> 2024-11-02 14:55:51.105 [info] resolve VitePress url: /home/veetaha/work/bon/website/src/reference/builder/member/into.md -> undefined
> 2024-11-02 14:55:51.105 [info] Resolved url: /home/veetaha/work/bon/website/src/reference/builder/member/into.md -> undefined
> 2024-11-02 14:55:55.152 [info] Resolved url: fantasy.vp-preview.VitePress Preview -> undefined
> ```
> 
> The logs stopped at this point

I think I figured it out, it should be caused by the workspace root path, I open `bon/website` as workspace root, however, you open `bon` as worksapce root

**Comment by 0x-jerry** [comment]
Confirmed, I can reproduce it by opening `bon` as the workspace root

**Comment by Veetaha** [comment]
```
Not in srcDir {"srcDir":"src","relativeFilePath":"/src/reference/builder/member/into.md"}
```
I think the problem is here. I added this log in `resolveVitePressUrl` in the `if (!relativeFilePath.startsWith(config.srcDir))`

**Comment by Veetaha** [comment]
The `/src` prefix doesn't match `src` here

**Comment by 0x-jerry** [comment]
Thanks for your help, I believe the latest version (v0.3.4) will fix this issue.

**Comment by 0x-jerry** [comment]
Please let me konw if it's not working.

**Comment by Veetaha** [comment]
Yep, it's fixed, thanks!
